
/*BELOW ARE COMMANDS,BUT!!!*/
/*THEY ACTUALLY GO INSIDE TERMINAL!! NOT USED HERE*/
/*JUST A REFERENCE PLEASE DONT GET CONFUSED!!!!*/

CREATE DATABASE pernstack;

CREATE TABLE todo(
todo_id SERIAL PRIMARY KEY,
 description VARCHAR(255)
 );
